//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroTargetSelectorResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstroTargetSelectorBusiness.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actualisation de la liste des objets célestes et recalcul des Scoring, Rank et Positions ....
        /// </summary>
        public static string ActualisationDeLaListeDesObjetsCelesteEtRecalculDesScoringRankEtPositions {
            get {
                return ResourceManager.GetString("ActualisationDeLaListeDesObjetsCelesteEtRecalculDesScoringRankEtPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la hauteur et la direction.
        /// </summary>
        public static string AfficherLaHauteurEtLaDirection {
            get {
                return ResourceManager.GetString("AfficherLaHauteurEtLaDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la mosaïque complète dans Cartes du Ciel.
        /// </summary>
        public static string AfficherLaMosaiqueCompleteDansCartesDuCiel {
            get {
                return ResourceManager.GetString("AfficherLaMosaiqueCompleteDansCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la mosaïque complète dans Stellarium.
        /// </summary>
        public static string AfficherLaMosaiqueCompleteDansStellarium {
            get {
                return ResourceManager.GetString("AfficherLaMosaiqueCompleteDansStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher le panneau sélectionné dans Cartes Du Ciel.
        /// </summary>
        public static string AfficherLePanneauSelectionneDansCartesDuCiel {
            get {
                return ResourceManager.GetString("AfficherLePanneauSelectionneDansCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher le panneau sélectionné dans Stellarium.
        /// </summary>
        public static string AfficherLePanneauSelectionneDansStellarium {
            get {
                return ResourceManager.GetString("AfficherLePanneauSelectionneDansStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste dans Cartes du Ciel..
        /// </summary>
        public static string AfficherLObjetCelesteDansCartesDuCiel {
            get {
                return ResourceManager.GetString("AfficherLObjetCelesteDansCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste dans Mosaic Calculator.
        /// </summary>
        public static string AfficherLObjetCelesteDansMosaicCalculator {
            get {
                return ResourceManager.GetString("AfficherLObjetCelesteDansMosaicCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste dans Stellarium..
        /// </summary>
        public static string AfficherLObjetCelesteDansStellarium {
            get {
                return ResourceManager.GetString("AfficherLObjetCelesteDansStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alt..
        /// </summary>
        public static string Alt {
            get {
                return ResourceManager.GetString("Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuel.
        /// </summary>
        public static string Annuel {
            get {
                return ResourceManager.GetString("Annuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos de.
        /// </summary>
        public static string AProposDe {
            get {
                return ResourceManager.GetString("AProposDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrêter le déplacement en cours.
        /// </summary>
        public static string ArreterLeDeplacementEnCours {
            get {
                return ResourceManager.GetString("ArreterLeDeplacementEnCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention, la rotation globale sur la durée totale de la mosaïque semble importante..
        /// </summary>
        public static string AttentionLaRotationGlobaleSurLaDureeTotaleDeLaMosaiqueSembleImportante {
            get {
                return ResourceManager.GetString("AttentionLaRotationGlobaleSurLaDureeTotaleDeLaMosaiqueSembleImportante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune.
        /// </summary>
        public static string Aucune {
            get {
                return ResourceManager.GetString("Aucune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun Rectangle sélectionné dans la liste.
        /// </summary>
        public static string AucunRectangleSelectionneDansLaListe {
            get {
                return ResourceManager.GetString("AucunRectangleSelectionneDansLaListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Az..
        /// </summary>
        public static string Az {
            get {
                return ResourceManager.GetString("Az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azimut.
        /// </summary>
        public static string Azimut {
            get {
                return ResourceManager.GetString("Azimut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bougé max..
        /// </summary>
        public static string BougeMax {
            get {
                return ResourceManager.GetString("BougeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capteur.
        /// </summary>
        public static string Capteur {
            get {
                return ResourceManager.GetString("Capteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à capteurs.
        /// </summary>
        public static string Capteurs {
            get {
                return ResourceManager.GetString("Capteurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre de la mosaïque.
        /// </summary>
        public static string CentreDeLaMosaique {
            get {
                return ResourceManager.GetString("CentreDeLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette fonctionnalité nécessite d&apos;avoir installé les pré-requis suivant :.
        /// </summary>
        public static string CetteFonctionnaliteNecessiteDAvoirInstalleLesPreRequisSuivant {
            get {
                return ResourceManager.GetString("CetteFonctionnaliteNecessiteDAvoirInstalleLesPreRequisSuivant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette opération peut prendre quelques instants.
        /// </summary>
        public static string CetteOperationPeutPrendreQuelquesInstants {
            get {
                return ResourceManager.GetString("CetteOperationPeutPrendreQuelquesInstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecter/Déconnecter le télescope ASCOM.
        /// </summary>
        public static string ConnecterDeconnecterLeTelescopeASCOM {
            get {
                return ResourceManager.GetString("ConnecterDeconnecterLeTelescopeASCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Constellation.
        /// </summary>
        public static string Constellation {
            get {
                return ResourceManager.GetString("Constellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contributeurs.
        /// </summary>
        public static string Contributeurs {
            get {
                return ResourceManager.GetString("Contributeurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couleurs de fenêtre.
        /// </summary>
        public static string CouleursDeFenetre {
            get {
                return ResourceManager.GetString("CouleursDeFenetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couleurs des polices.
        /// </summary>
        public static string CouleursDesPolices {
            get {
                return ResourceManager.GetString("CouleursDesPolices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de l&apos;observation.
        /// </summary>
        public static string DateDeLObservation {
            get {
                return ResourceManager.GetString("DateDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date et heure de l&apos;observation.
        /// </summary>
        public static string DateEtHeureDeLObservation {
            get {
                return ResourceManager.GetString("DateEtHeureDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DEC.
        /// </summary>
        public static string DEC {
            get {
                return ResourceManager.GetString("DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DEC (J2000).
        /// </summary>
        public static string DECJ2000 {
            get {
                return ResourceManager.GetString("DECJ2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer l&apos;application AstroSessionOrganizer.
        /// </summary>
        public static string DemarrerLApplicationAstroSessionOrganizer {
            get {
                return ResourceManager.GetString("DemarrerLApplicationAstroSessionOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dimension au mauvais format.
        /// </summary>
        public static string DimensionAuMauvaisFormat {
            get {
                return ResourceManager.GetString("DimensionAuMauvaisFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Divers.
        /// </summary>
        public static string Divers {
            get {
                return ResourceManager.GetString("Divers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée d&apos;un intervalle.
        /// </summary>
        public static string DureeDUnIntervalle {
            get {
                return ResourceManager.GetString("DureeDUnIntervalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée totale.
        /// </summary>
        public static string DureeTotale {
            get {
                return ResourceManager.GetString("DureeTotale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à effectué avec succès.
        /// </summary>
        public static string EffectueAvecSucces {
            get {
                return ResourceManager.GetString("EffectueAvecSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande....
        /// </summary>
        public static string EnvoiDeLaCommande {
            get {
                return ResourceManager.GetString("EnvoiDeLaCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Estimation de la largeur totale de la mosaïque.
        /// </summary>
        public static string EstimationDeLaLargeurTotaleDeLaMosaique {
            get {
                return ResourceManager.GetString("EstimationDeLaLargeurTotaleDeLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Estimation de la rotation globale de l&apos;objet sur la session.
        /// </summary>
        public static string EstimationDeLaRotationGlobaleDeLObjetSurLaSession {
            get {
                return ResourceManager.GetString("EstimationDeLaRotationGlobaleDeLObjetSurLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exporter.
        /// </summary>
        public static string Exporter {
            get {
                return ResourceManager.GetString("Exporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exporter les résultats.
        /// </summary>
        public static string ExporterLesResultats {
            get {
                return ResourceManager.GetString("ExporterLesResultats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export impossible : aucun panneau dans la mosaïque.
        /// </summary>
        public static string ExportImpossibleAucunPanneauDansLaMosaique {
            get {
                return ResourceManager.GetString("ExportImpossibleAucunPanneauDansLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        public static string Fermer {
            get {
                return ResourceManager.GetString("Fermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtrer les résultats.
        /// </summary>
        public static string FiltrerLesResultats {
            get {
                return ResourceManager.GetString("FiltrerLesResultats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à F : longueur focale en mm.
        /// </summary>
        public static string FLongueurFocale {
            get {
                return ResourceManager.GetString("FLongueurFocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format des champs pour le plugin Stellarium incorrect.
        /// </summary>
        public static string FormatDesChampsPourLePluginStellariumIncorrect {
            get {
                return ResourceManager.GetString("FormatDesChampsPourLePluginStellariumIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du Capteur incorrect.
        /// </summary>
        public static string FormatDuCapteurIncorrect {
            get {
                return ResourceManager.GetString("FormatDuCapteurIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ &quot;Bougé max.&quot; incorrect.
        /// </summary>
        public static string FormatDuChampBougeMaxIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampBougeMaxIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ DEC incorrect.
        /// </summary>
        public static string FormatDuChampDECIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampDECIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ &quot;Hauteur minimum&quot; incorrect.
        /// </summary>
        public static string FormatDuChampHauteurMinIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampHauteurMinIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Largeur incorrect.
        /// </summary>
        public static string FormatDuChampLargeurIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampLargeurIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ RA incorrect.
        /// </summary>
        public static string FormatDuChampRAIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampRAIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Serveur pour Cartes du Ciel incorrect.
        /// </summary>
        public static string FormatDuChampServeurPourCartesDuCielIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampServeurPourCartesDuCielIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du lieu d&apos;observation incorrect.
        /// </summary>
        public static string FormatDuLieuDObservationIncorrect {
            get {
                return ResourceManager.GetString("FormatDuLieuDObservationIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format incorrect :.
        /// </summary>
        public static string FormatIncorrect {
            get {
                return ResourceManager.GetString("FormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FOV.
        /// </summary>
        public static string FOV {
            get {
                return ResourceManager.GetString("FOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FOV au mauvais format.
        /// </summary>
        public static string FOVAuMauvaisFormat {
            get {
                return ResourceManager.GetString("FOVAuMauvaisFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FOV = 57.3 * L / F.
        /// </summary>
        public static string FOVFormule {
            get {
                return ResourceManager.GetString("FOVFormule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grandeur (H).
        /// </summary>
        public static string GrandeurH {
            get {
                return ResourceManager.GetString("GrandeurH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grandeur (L).
        /// </summary>
        public static string GrandeurL {
            get {
                return ResourceManager.GetString("GrandeurL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur.
        /// </summary>
        public static string Hauteur {
            get {
                return ResourceManager.GetString("Hauteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur apparente minimum.
        /// </summary>
        public static string HauteurApparenteMinimum {
            get {
                return ResourceManager.GetString("HauteurApparenteMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur et direction.
        /// </summary>
        public static string HauteurEtDirection {
            get {
                return ResourceManager.GetString("HauteurEtDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur min..
        /// </summary>
        public static string HauteurMin {
            get {
                return ResourceManager.GetString("HauteurMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure.
        /// </summary>
        public static string Heure {
            get {
                return ResourceManager.GetString("Heure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à heure(s).
        /// </summary>
        public static string Heures {
            get {
                return ResourceManager.GetString("Heures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horaire.
        /// </summary>
        public static string Horaire {
            get {
                return ResourceManager.GetString("Horaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inclure les liens pour téléscopes Unistellar.
        /// </summary>
        public static string InclureLesLiensPourTelescopesUnistellar {
            get {
                return ResourceManager.GetString("InclureLesLiensPourTelescopesUnistellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index non fourni.
        /// </summary>
        public static string IndexNonFourni {
            get {
                return ResourceManager.GetString("IndexNonFourni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner votre capteur..
        /// </summary>
        public static string InfoCapteur1 {
            get {
                return ResourceManager.GetString("InfoCapteur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si votre capteur n&apos;est pas présent dans la liste, vous pouvez saisir manuellement le nom et la largeur en pixel..
        /// </summary>
        public static string InfoCapteur2 {
            get {
                return ResourceManager.GetString("InfoCapteur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur le FOV.
        /// </summary>
        public static string InformationsSurLeFOV {
            get {
                return ResourceManager.GetString("InformationsSurLeFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur le pilotage du télescope ASCOM.
        /// </summary>
        public static string InformationsSurLePilotageDuTelescopeASCOM {
            get {
                return ResourceManager.GetString("InformationsSurLePilotageDuTelescopeASCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date et l&apos;heure utilisées pour la création de la mosaïque correspondent à celles utilisées pour l&apos;observation horaire..
        /// </summary>
        public static string LaDateEtLHeureUtiliseesPourLaCreationDeLaMosaiqueCorrespondentACellesUtiliseesPourLObservationHoraire {
            get {
                return ResourceManager.GetString("LaDateEtLHeureUtiliseesPourLaCreationDeLaMosaiqueCorrespondentACellesUtiliseesPou" +
                        "rLObservationHoraire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - la plateforme ASCOM 6.6.
        /// </summary>
        public static string LaPlateformeASCOM {
            get {
                return ResourceManager.GetString("LaPlateformeASCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur.
        /// </summary>
        public static string Largeur {
            get {
                return ResourceManager.GetString("Largeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur de la mosaïque.
        /// </summary>
        public static string LargeurDeLaMosaique {
            get {
                return ResourceManager.GetString("LargeurDeLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur (px).
        /// </summary>
        public static string LargeurPX {
            get {
                return ResourceManager.GetString("LargeurPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du port doit correspondre à celle positionnée dans Stellarium, par défaut &apos;8090&apos;..
        /// </summary>
        public static string LaValeurDuPortDoitCorrespondreACellePositionneeDansStellariumParDefaut8090 {
            get {
                return ResourceManager.GetString("LaValeurDuPortDoitCorrespondreACellePositionneeDansStellariumParDefaut8090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le calcul de la mosaïque donne un nombre de panneaux trop important (&gt; 120)..
        /// </summary>
        public static string LeCalculDeLaMosaiqueDonneUnNombreDePanneauxTropImportant {
            get {
                return ResourceManager.GetString("LeCalculDeLaMosaiqueDonneUnNombreDePanneauxTropImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - le driver ASCOM de votre télescope.
        /// </summary>
        public static string LeDriverASCOMDeVotreTelescope {
            get {
                return ResourceManager.GetString("LeDriverASCOMDeVotreTelescope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les boutons Stellarium et Cartes du Ciel vous permettent de positionner ces logiciels sur les coordonnées du panneau sélectionné..
        /// </summary>
        public static string LesBoutonsStellariumEtCartesDuCielVousPermettentDePositionnerCesLogicielsSurLesCoordonneesDuPanneauSelectionne {
            get {
                return ResourceManager.GetString("LesBoutonsStellariumEtCartesDuCielVousPermettentDePositionnerCesLogicielsSurLesCo" +
                        "ordonneesDuPanneauSelectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les intervalles qui apparaissent en gris signifient que l&apos;objet est entré dans une zone exclue de votre ciel, ou que sa hauteur est en dessous de la hauteur minimum..
        /// </summary>
        public static string LesIntervallesQuiApparaissentEnGrisSignifientQueLObjetEstDntreDansUneZoneExclueDeVotreCielOuQueSaHauteurEstEnDessousDeLaHauteurMinimum {
            get {
                return ResourceManager.GetString("LesIntervallesQuiApparaissentEnGrisSignifientQueLObjetEstDntreDansUneZoneExclueDe" +
                        "VotreCielOuQueSaHauteurEstEnDessousDeLaHauteurMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lien.
        /// </summary>
        public static string Lien {
            get {
                return ResourceManager.GetString("Lien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liens Unistellar.
        /// </summary>
        public static string LiensUnistellar {
            get {
                return ResourceManager.GetString("LiensUnistellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu.
        /// </summary>
        public static string Lieu {
            get {
                return ResourceManager.GetString("Lieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu de l&apos;observation.
        /// </summary>
        public static string LieuDeLObservation {
            get {
                return ResourceManager.GetString("LieuDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu de l&apos;observation (Lat. - Long.).
        /// </summary>
        public static string LieuDeLObservationLatLong {
            get {
                return ResourceManager.GetString("LieuDeLObservationLatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L : largeur de votre capteur en µm.
        /// </summary>
        public static string LLargeurDeVotreCapteur {
            get {
                return ResourceManager.GetString("LLargeurDeVotreCapteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lune.
        /// </summary>
        public static string Lune {
            get {
                return ResourceManager.GetString("Lune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnitude.
        /// </summary>
        public static string Magnitude {
            get {
                return ResourceManager.GetString("Magnitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnitude max..
        /// </summary>
        public static string MagnitudeMax {
            get {
                return ResourceManager.GetString("MagnitudeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mensuel.
        /// </summary>
        public static string Mensuel {
            get {
                return ResourceManager.GetString("Mensuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Actualiser la liste des objets célestes.
        /// </summary>
        public static string menuActualiserLaListeDesObjetsCelestes {
            get {
                return ResourceManager.GetString("menuActualiserLaListeDesObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Affichage.
        /// </summary>
        public static string menuAffichage {
            get {
                return ResourceManager.GetString("menuAffichage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;A propos.
        /// </summary>
        public static string menuAPropos {
            get {
                return ResourceManager.GetString("menuAPropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Fichier.
        /// </summary>
        public static string menuFichier {
            get {
                return ResourceManager.GetString("menuFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre à jour le catalogue des &amp;objets célestes.
        /// </summary>
        public static string menuMettreAJourLeCatalogueDesObjetsCelestes {
            get {
                return ResourceManager.GetString("menuMettreAJourLeCatalogueDesObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre à jour le catalogue des &amp;capteurs.
        /// </summary>
        public static string menuMettreJourLeCatalogueDesCapteurs {
            get {
                return ResourceManager.GetString("menuMettreJourLeCatalogueDesCapteurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode &amp;nuit.
        /// </summary>
        public static string menuModeNuit {
            get {
                return ResourceManager.GetString("menuModeNuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Outils.
        /// </summary>
        public static string menuOutils {
            get {
                return ResourceManager.GetString("menuOutils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Paramètres de l&apos;observation.
        /// </summary>
        public static string menuParametresDeLObservation {
            get {
                return ResourceManager.GetString("menuParametresDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Quitter.
        /// </summary>
        public static string menuQuitter {
            get {
                return ResourceManager.GetString("menuQuitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à min..
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour des fichiers de configuration.
        /// </summary>
        public static string MiseAJourDesFichiersDeConfiguration {
            get {
                return ResourceManager.GetString("MiseAJourDesFichiersDeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour du fichier de configuration des.
        /// </summary>
        public static string MiseAJourDuFichierDeConfigurationDes {
            get {
                return ResourceManager.GetString("MiseAJourDuFichierDeConfigurationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier la taille de la mosaïque.
        /// </summary>
        public static string ModifierLaTailleDeLaMosaique {
            get {
                return ResourceManager.GetString("ModifierLaTailleDeLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier les coordonnées du centre de la mosaïque.
        /// </summary>
        public static string ModifierLesCoordonneesDuCentreDeLaMosaique {
            get {
                return ResourceManager.GetString("ModifierLesCoordonneesDuCentreDeLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mosaic Calculator.
        /// </summary>
        public static string MosaicCalculator {
            get {
                return ResourceManager.GetString("MosaicCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mosaïque incorrecte.
        /// </summary>
        public static string MosaiqueIncorrecte {
            get {
                return ResourceManager.GetString("MosaiqueIncorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau de chevauchement des images.
        /// </summary>
        public static string NiveauDeChevauchementDesImages {
            get {
                return ResourceManager.GetString("NiveauDeChevauchementDesImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de panneaux.
        /// </summary>
        public static string NombreDePanneaux {
            get {
                return ResourceManager.GetString("NombreDePanneaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de paramètres incorrect.
        /// </summary>
        public static string NombreDeParametresIncorrect {
            get {
                return ResourceManager.GetString("NombreDeParametresIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom panneau.
        /// </summary>
        public static string NomPanneau {
            get {
                return ResourceManager.GetString("NomPanneau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous vous conseillons de planifier votre mosaïque en plusieurs soirées, en privilégiant les mêmes plages horaires..
        /// </summary>
        public static string NousVousConseillonsDePlanifierVotreMosaiqueEnPlusieursSoireesEnPrivilegiantLesMemesPlagesHoraires {
            get {
                return ResourceManager.GetString("NousVousConseillonsDePlanifierVotreMosaiqueEnPlusieursSoireesEnPrivilegiantLesMem" +
                        "esPlagesHoraires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle version disponible.
        /// </summary>
        public static string NouvelleVersionDisponible {
            get {
                return ResourceManager.GetString("NouvelleVersionDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nuits.
        /// </summary>
        public static string Nuits {
            get {
                return ResourceManager.GetString("Nuits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet céleste.
        /// </summary>
        public static string ObjetCeleste {
            get {
                return ResourceManager.GetString("ObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet céleste et paramètres de la mosaïque.
        /// </summary>
        public static string ObjetCelesteEtParametresDeLaMosaique {
            get {
                return ResourceManager.GetString("ObjetCelesteEtParametresDeLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à objets célestes.
        /// </summary>
        public static string ObjetsCelestes {
            get {
                return ResourceManager.GetString("ObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet sélectionné.
        /// </summary>
        public static string ObjetSelectionne {
            get {
                return ResourceManager.GetString("ObjetSelectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Orienter votre télescope ASCOM sur le panneau sélectionné.
        /// </summary>
        public static string OrienterVotreTelescopeASCOMSurLePanneauSelectionne {
            get {
                return ResourceManager.GetString("OrienterVotreTelescopeASCOMSurLePanneauSelectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir le fichier des &amp;logs.
        /// </summary>
        public static string OuvrirLeFichierDesLogs {
            get {
                return ResourceManager.GetString("OuvrirLeFichierDesLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panneau.
        /// </summary>
        public static string Panneau {
            get {
                return ResourceManager.GetString("Panneau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string Parametres {
            get {
                return ResourceManager.GetString("Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres de Cartes Du Ciel.
        /// </summary>
        public static string ParametresDeCartesDuCiel {
            get {
                return ResourceManager.GetString("ParametresDeCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres de l&apos;observation.
        /// </summary>
        public static string ParametresDeLObservation {
            get {
                return ResourceManager.GetString("ParametresDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres des planétariums (Stellarium / Cartes du Ciel).
        /// </summary>
        public static string ParametresDesPlanetariumsStellariumCartesDuCiel {
            get {
                return ResourceManager.GetString("ParametresDesPlanetariumsStellariumCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres du plugin de contrôle à distance de Stellarium.
        /// </summary>
        public static string ParametresDuPluginDeControleQDistanceDeStellarium {
            get {
                return ResourceManager.GetString("ParametresDuPluginDeControleQDistanceDeStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnalisation de l&apos;affichage en mode nuit.
        /// </summary>
        public static string PersonnalisationDeLAffichageEnModeNuit {
            get {
                return ResourceManager.GetString("PersonnalisationDeLAffichageEnModeNuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positionnez ici les informations nécessaires à la connexion au plugin de commande à distance de Stellarium..
        /// </summary>
        public static string PositionnezIciLesOnformationsNecessairesALaConnexionAuPluginDeCommandeADistanceDeStellarium {
            get {
                return ResourceManager.GetString("PositionnezIciLesOnformationsNecessairesALaConnexionAuPluginDeCommandeADistanceDe" +
                        "Stellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour exécuter Cartes du Ciel directement sur cet ordinateur, laissez la valeur par défaut &apos;127.0.0.1&apos;..
        /// </summary>
        public static string PourExecuterCartesDuCielDirectementSurCetOrdinateurLaissezLaValeurParDefaut127001 {
            get {
                return ResourceManager.GetString("PourExecuterCartesDuCielDirectementSurCetOrdinateurLaissezLaValeurParDefaut127001" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour exécuter Stellarium directement sur cet ordinateur, laissez la valeur par défaut &apos;localhost&apos;..
        /// </summary>
        public static string PourExecuterStellariumDirectementSurCetOrdinateurLaissezLaValeurParDefautLocalhost {
            get {
                return ResourceManager.GetString("PourExecuterStellariumDirectementSurCetOrdinateurLaissezLaValeurParDefautLocalhos" +
                        "t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour vous connecter à Cartes du Ciel sur un serveur, spécifiez ici l&apos;adresse IP du serveur..
        /// </summary>
        public static string PourVousConnecterACartesDuCielSurUnServeurSpecifiezIciLAdresseIPDuServeur {
            get {
                return ResourceManager.GetString("PourVousConnecterACartesDuCielSurUnServeurSpecifiezIciLAdresseIPDuServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RA.
        /// </summary>
        public static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RA (J2000).
        /// </summary>
        public static string RAJ2000 {
            get {
                return ResourceManager.GetString("RAJ2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rank min..
        /// </summary>
        public static string RankMin {
            get {
                return ResourceManager.GetString("RankMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restaurer les valeurs par défaut.
        /// </summary>
        public static string RestaurerLesValeursParDefaut {
            get {
                return ResourceManager.GetString("RestaurerLesValeursParDefaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résultats du calcul de la mosaïque.
        /// </summary>
        public static string ResultatsDuCalculDeLaMosaique {
            get {
                return ResourceManager.GetString("ResultatsDuCalculDeLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scoring.
        /// </summary>
        public static string Scoring {
            get {
                return ResourceManager.GetString("Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection du Capteur.
        /// </summary>
        public static string SelectionDuCapteur {
            get {
                return ResourceManager.GetString("SelectionDuCapteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection d&apos;un élément dans la liste.
        /// </summary>
        public static string SelectionDUnElémentDansLaListe {
            get {
                return ResourceManager.GetString("SelectionDUnElémentDansLaListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez un panneau dans la liste afin de l&apos;afficher dans la mosaïque..
        /// </summary>
        public static string SelectionnezUnPanneauDansLaListeAfinDeLAfficherDansLaMosaique {
            get {
                return ResourceManager.GetString("SelectionnezUnPanneauDansLaListeAfinDeLAfficherDansLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serveur.
        /// </summary>
        public static string Serveur {
            get {
                return ResourceManager.GetString("Serveur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soleil.
        /// </summary>
        public static string Soleil {
            get {
                return ResourceManager.GetString("Soleil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soleil et Lune.
        /// </summary>
        public static string SoleilEtLune {
            get {
                return ResourceManager.GetString("SoleilEtLune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        public static string Suivant {
            get {
                return ResourceManager.GetString("Suivant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taux de chevauchement au mauvais format.
        /// </summary>
        public static string TauxDeChevauchementAuMauvaisFormat {
            get {
                return ResourceManager.GetString("TauxDeChevauchementAuMauvaisFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télescope ASCOM.
        /// </summary>
        public static string TelescopeASCOM {
            get {
                return ResourceManager.GetString("TelescopeASCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose.
        /// </summary>
        public static string TempsDePose {
            get {
                return ResourceManager.GetString("TempsDePose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose max..
        /// </summary>
        public static string TempsDePoseMax {
            get {
                return ResourceManager.GetString("TempsDePoseMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose par panneau.
        /// </summary>
        public static string TempsDePoseParPanneau {
            get {
                return ResourceManager.GetString("TempsDePoseParPanneau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose par panneau au mauvais format.
        /// </summary>
        public static string TempsDePoseParPanneauAuMauvaisFormat {
            get {
                return ResourceManager.GetString("TempsDePoseParPanneauAuMauvaisFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose (secondes) sans rotation de champs.
        /// </summary>
        public static string TempsDePoseSecondesSansRotationDeChamps {
            get {
                return ResourceManager.GetString("TempsDePoseSecondesSansRotationDeChamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose total pour la mosaïque.
        /// </summary>
        public static string TempsDePoseTotalPourLaMosaique {
            get {
                return ResourceManager.GetString("TempsDePoseTotalPourLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer.
        /// </summary>
        public static string Terminer {
            get {
                return ResourceManager.GetString("Terminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tons clairs.
        /// </summary>
        public static string TonsClairs {
            get {
                return ResourceManager.GetString("TonsClairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tons sombres.
        /// </summary>
        public static string TonsSombres {
            get {
                return ResourceManager.GetString("TonsSombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        public static string Tous {
            get {
                return ResourceManager.GetString("Tous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trop de panneaux dans la mosaïque.
        /// </summary>
        public static string TropDePanneauxDansLaMosaique {
            get {
                return ResourceManager.GetString("TropDePanneauxDansLaMosaique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors du téléchargement. Fichier téléchargé non présent.
        /// </summary>
        public static string UneErreurEstSurvenueLorsDuTelechargementFichierTelechargeNonPresent {
            get {
                return ResourceManager.GetString("UneErreurEstSurvenueLorsDuTelechargementFichierTelechargeNonPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valeur incorrecte :.
        /// </summary>
        public static string ValeurIncorrecte {
            get {
                return ResourceManager.GetString("ValeurIncorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez spécifier une valeur décicmale positive..
        /// </summary>
        public static string VeuillezSpecifierUneValeurDecicmalePositive {
            get {
                return ResourceManager.GetString("VeuillezSpecifierUneValeurDecicmalePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez spécifier un nombre entier compris entre 1 et 240..
        /// </summary>
        public static string VeuillezSpecifierUnNombreEntierComprisEntre1Et240 {
            get {
                return ResourceManager.GetString("VeuillezSpecifierUnNombreEntierComprisEntre1Et240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez spécifier un nombre entier compris entre 1 et 50..
        /// </summary>
        public static string VeuillezSpecifierUnNombreEntierComprisEntre1Et50 {
            get {
                return ResourceManager.GetString("VeuillezSpecifierUnNombreEntierComprisEntre1Et50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visualisation.
        /// </summary>
        public static string Visualisation {
            get {
                return ResourceManager.GetString("Visualisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voici la formule vous permettant de calculer votre champ de vision (FOV) :.
        /// </summary>
        public static string VoiciLaFormuleVousPermettantDeCalculerVotreChampDeVision {
            get {
                return ResourceManager.GetString("VoiciLaFormuleVousPermettantDeCalculerVotreChampDeVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous aller télécharger et mettre à jour le fichier de configuration des.
        /// </summary>
        public static string VousAllerTeléchargerEtMettreAJourLeFichierDeConfigurationDes {
            get {
                return ResourceManager.GetString("VousAllerTeléchargerEtMettreAJourLeFichierDeConfigurationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zones du ciel exclues.
        /// </summary>
        public static string ZonesDuCielExclues {
            get {
                return ResourceManager.GetString("ZonesDuCielExclues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zones exclues.
        /// </summary>
        public static string ZonesExclues {
            get {
                return ResourceManager.GetString("ZonesExclues", resourceCulture);
            }
        }
    }
}
