//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroTargetSelectorResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstroTargetSelectorBusiness.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actualisation de la liste des objets célestes et recalcul des Scoring, Rank et Positions ....
        /// </summary>
        public static string ActualisationDeLaListeDesObjetsCelesteEtRecalculDesScoringRankEtPositions {
            get {
                return ResourceManager.GetString("ActualisationDeLaListeDesObjetsCelesteEtRecalculDesScoringRankEtPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la hauteur et la direction.
        /// </summary>
        public static string AfficherLaHauteurEtLaDirection {
            get {
                return ResourceManager.GetString("AfficherLaHauteurEtLaDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste dans Cartes du Ciel..
        /// </summary>
        public static string AfficherLObjetCelesteDansCartesDuCiel {
            get {
                return ResourceManager.GetString("AfficherLObjetCelesteDansCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste dans Stellarium..
        /// </summary>
        public static string AfficherLObjetCelesteDansStellarium {
            get {
                return ResourceManager.GetString("AfficherLObjetCelesteDansStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuel.
        /// </summary>
        public static string Annuel {
            get {
                return ResourceManager.GetString("Annuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos de.
        /// </summary>
        public static string AProposDe {
            get {
                return ResourceManager.GetString("AProposDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune.
        /// </summary>
        public static string Aucune {
            get {
                return ResourceManager.GetString("Aucune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Azimut.
        /// </summary>
        public static string Azimut {
            get {
                return ResourceManager.GetString("Azimut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bougé max..
        /// </summary>
        public static string BougeMax {
            get {
                return ResourceManager.GetString("BougeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capteur.
        /// </summary>
        public static string Capteur {
            get {
                return ResourceManager.GetString("Capteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à capteurs.
        /// </summary>
        public static string Capteurs {
            get {
                return ResourceManager.GetString("Capteurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette opération peut prendre quelques instants.
        /// </summary>
        public static string CetteOperationPeutPrendreQuelquesInstants {
            get {
                return ResourceManager.GetString("CetteOperationPeutPrendreQuelquesInstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Constellation.
        /// </summary>
        public static string Constellation {
            get {
                return ResourceManager.GetString("Constellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contributeurs.
        /// </summary>
        public static string Contributeurs {
            get {
                return ResourceManager.GetString("Contributeurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de l&apos;observation.
        /// </summary>
        public static string DateDeLObservation {
            get {
                return ResourceManager.GetString("DateDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date et heure de l&apos;observation.
        /// </summary>
        public static string DateEtHeureDeLObservation {
            get {
                return ResourceManager.GetString("DateEtHeureDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DEC.
        /// </summary>
        public static string DEC {
            get {
                return ResourceManager.GetString("DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DEC (J2000).
        /// </summary>
        public static string DECJ2000 {
            get {
                return ResourceManager.GetString("DECJ2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer l&apos;application AstroSessionOrganizer.
        /// </summary>
        public static string DemarrerLApplicationAstroSessionOrganizer {
            get {
                return ResourceManager.GetString("DemarrerLApplicationAstroSessionOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Divers.
        /// </summary>
        public static string Divers {
            get {
                return ResourceManager.GetString("Divers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée d&apos;un intervalle.
        /// </summary>
        public static string DureeDUnIntervalle {
            get {
                return ResourceManager.GetString("DureeDUnIntervalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée totale.
        /// </summary>
        public static string DureeTotale {
            get {
                return ResourceManager.GetString("DureeTotale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à effectué avec succès.
        /// </summary>
        public static string EffectueAvecSucces {
            get {
                return ResourceManager.GetString("EffectueAvecSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande....
        /// </summary>
        public static string EnvoiDeLaCommande {
            get {
                return ResourceManager.GetString("EnvoiDeLaCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtrer les résultats.
        /// </summary>
        public static string FiltrerLesResultats {
            get {
                return ResourceManager.GetString("FiltrerLesResultats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format des champs pour le plugin Stellarium incorrect.
        /// </summary>
        public static string FormatDesChampsPourLePluginStellariumIncorrect {
            get {
                return ResourceManager.GetString("FormatDesChampsPourLePluginStellariumIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du Capteur incorrect.
        /// </summary>
        public static string FormatDuCapteurIncorrect {
            get {
                return ResourceManager.GetString("FormatDuCapteurIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ &quot;Bougé max.&quot; incorrect.
        /// </summary>
        public static string FormatDuChampBougeMaxIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampBougeMaxIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ &quot;Hauteur minimum&quot; incorrect.
        /// </summary>
        public static string FormatDuChampHauteurMinIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampHauteurMinIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Serveur pour Cartes du Ciel incorrect.
        /// </summary>
        public static string FormatDuChampServeurPourCartesDuCielIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampServeurPourCartesDuCielIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du lieu d&apos;observation incorrect.
        /// </summary>
        public static string FormatDuLieuDObservationIncorrect {
            get {
                return ResourceManager.GetString("FormatDuLieuDObservationIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grandeur (H).
        /// </summary>
        public static string GrandeurH {
            get {
                return ResourceManager.GetString("GrandeurH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grandeur (L).
        /// </summary>
        public static string GrandeurL {
            get {
                return ResourceManager.GetString("GrandeurL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur.
        /// </summary>
        public static string Hauteur {
            get {
                return ResourceManager.GetString("Hauteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur apparente minimum.
        /// </summary>
        public static string HauteurApparenteMinimum {
            get {
                return ResourceManager.GetString("HauteurApparenteMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hauteur min..
        /// </summary>
        public static string HauteurMin {
            get {
                return ResourceManager.GetString("HauteurMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure.
        /// </summary>
        public static string Heure {
            get {
                return ResourceManager.GetString("Heure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à heure(s).
        /// </summary>
        public static string Heures {
            get {
                return ResourceManager.GetString("Heures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horaire.
        /// </summary>
        public static string Horaire {
            get {
                return ResourceManager.GetString("Horaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner votre capteur..
        /// </summary>
        public static string InfoCapteur1 {
            get {
                return ResourceManager.GetString("InfoCapteur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si votre capteur n&apos;est pas présent dans la liste, vous pouvez saisir manuellement le nom et la largeur en pixel..
        /// </summary>
        public static string InfoCapteur2 {
            get {
                return ResourceManager.GetString("InfoCapteur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur.
        /// </summary>
        public static string Largeur {
            get {
                return ResourceManager.GetString("Largeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Largeur (px).
        /// </summary>
        public static string LargeurPX {
            get {
                return ResourceManager.GetString("LargeurPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du port doit correspondre à celle positionnée dans Stellarium, par défaut &apos;8090&apos;..
        /// </summary>
        public static string LaValeurDuPortDoitCorrespondreACellePositionneeDansStellariumParDefaut8090 {
            get {
                return ResourceManager.GetString("LaValeurDuPortDoitCorrespondreACellePositionneeDansStellariumParDefaut8090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les intervalles qui apparaissent en gris signifient que l&apos;objet est entré dans une zone exclue de votre ciel, ou que sa hauteur est en dessous de la hauteur minimum..
        /// </summary>
        public static string LesIntervallesQuiApparaissentEnGrisSignifientQueLObjetEstDntreDansUneZoneExclueDeVotreCielOuQueSaHauteurEstEnDessousDeLaHauteurMinimum {
            get {
                return ResourceManager.GetString("LesIntervallesQuiApparaissentEnGrisSignifientQueLObjetEstDntreDansUneZoneExclueDe" +
                        "VotreCielOuQueSaHauteurEstEnDessousDeLaHauteurMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu.
        /// </summary>
        public static string Lieu {
            get {
                return ResourceManager.GetString("Lieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu de l&apos;observation.
        /// </summary>
        public static string LieuDeLObservation {
            get {
                return ResourceManager.GetString("LieuDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu de l&apos;observation (Lat. - Long.).
        /// </summary>
        public static string LieuDeLObservationLatLong {
            get {
                return ResourceManager.GetString("LieuDeLObservationLatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnitude.
        /// </summary>
        public static string Magnitude {
            get {
                return ResourceManager.GetString("Magnitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnitude max..
        /// </summary>
        public static string MagnitudeMax {
            get {
                return ResourceManager.GetString("MagnitudeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mensuel.
        /// </summary>
        public static string Mensuel {
            get {
                return ResourceManager.GetString("Mensuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Actualiser la liste des objets célestes.
        /// </summary>
        public static string menuActualiserLaListeDesObjetsCelestes {
            get {
                return ResourceManager.GetString("menuActualiserLaListeDesObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Affichage.
        /// </summary>
        public static string menuAffichage {
            get {
                return ResourceManager.GetString("menuAffichage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;A propos.
        /// </summary>
        public static string menuAPropos {
            get {
                return ResourceManager.GetString("menuAPropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Fichier.
        /// </summary>
        public static string menuFichier {
            get {
                return ResourceManager.GetString("menuFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre à jour le catalogue des &amp;objets célestes.
        /// </summary>
        public static string menuMettreAJourLeCatalogueDesObjetsCelestes {
            get {
                return ResourceManager.GetString("menuMettreAJourLeCatalogueDesObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre à jour le catalogue des &amp;capteurs.
        /// </summary>
        public static string menuMettreJourLeCatalogueDesCapteurs {
            get {
                return ResourceManager.GetString("menuMettreJourLeCatalogueDesCapteurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode &amp;nuit.
        /// </summary>
        public static string menuModeNuit {
            get {
                return ResourceManager.GetString("menuModeNuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Outils.
        /// </summary>
        public static string menuOutils {
            get {
                return ResourceManager.GetString("menuOutils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Paramètres de l&apos;observation.
        /// </summary>
        public static string menuParametresDeLObservation {
            get {
                return ResourceManager.GetString("menuParametresDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Quitter.
        /// </summary>
        public static string menuQuitter {
            get {
                return ResourceManager.GetString("menuQuitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour des fichiers de configuration.
        /// </summary>
        public static string MiseAJourDesFichiersDeConfiguration {
            get {
                return ResourceManager.GetString("MiseAJourDesFichiersDeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour du fichier de configuration des.
        /// </summary>
        public static string MiseAJourDuFichierDeConfigurationDes {
            get {
                return ResourceManager.GetString("MiseAJourDuFichierDeConfigurationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de paramètres incorrect.
        /// </summary>
        public static string NombreDeParametresIncorrect {
            get {
                return ResourceManager.GetString("NombreDeParametresIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle version disponible.
        /// </summary>
        public static string NouvelleVersionDisponible {
            get {
                return ResourceManager.GetString("NouvelleVersionDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nuits.
        /// </summary>
        public static string Nuits {
            get {
                return ResourceManager.GetString("Nuits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet céleste.
        /// </summary>
        public static string ObjetCeleste {
            get {
                return ResourceManager.GetString("ObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à objets célestes.
        /// </summary>
        public static string ObjetsCelestes {
            get {
                return ResourceManager.GetString("ObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet sélectionné.
        /// </summary>
        public static string ObjetSelectionne {
            get {
                return ResourceManager.GetString("ObjetSelectionne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir le fichier des &amp;logs.
        /// </summary>
        public static string OuvrirLeFichierDesLogs {
            get {
                return ResourceManager.GetString("OuvrirLeFichierDesLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string Parametres {
            get {
                return ResourceManager.GetString("Parametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres de Cartes Du Ciel.
        /// </summary>
        public static string ParametresDeCartesDuCiel {
            get {
                return ResourceManager.GetString("ParametresDeCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres de l&apos;observation.
        /// </summary>
        public static string ParametresDeLObservation {
            get {
                return ResourceManager.GetString("ParametresDeLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres des planétariums (Stellarium / Cartes du Ciel).
        /// </summary>
        public static string ParametresDesPlanetariumsStellariumCartesDuCiel {
            get {
                return ResourceManager.GetString("ParametresDesPlanetariumsStellariumCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres du plugin de contrôle à distance de Stellarium.
        /// </summary>
        public static string ParametresDuPluginDeControleQDistanceDeStellarium {
            get {
                return ResourceManager.GetString("ParametresDuPluginDeControleQDistanceDeStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positionnez ici les informations nécessaires à la connexion au plugin de commande à distance de Stellarium..
        /// </summary>
        public static string PositionnezIciLesOnformationsNecessairesALaConnexionAuPluginDeCommandeADistanceDeStellarium {
            get {
                return ResourceManager.GetString("PositionnezIciLesOnformationsNecessairesALaConnexionAuPluginDeCommandeADistanceDe" +
                        "Stellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour exécuter Cartes du Ciel directement sur cet ordinateur, laissez la valeur par défaut &apos;127.0.0.1&apos;..
        /// </summary>
        public static string PourExecuterCartesDuCielDirectementSurCetOrdinateurLaissezLaValeurParDefaut127001 {
            get {
                return ResourceManager.GetString("PourExecuterCartesDuCielDirectementSurCetOrdinateurLaissezLaValeurParDefaut127001" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour exécuter Stellarium directement sur cet ordinateur, laissez la valeur par défaut &apos;localhost&apos;..
        /// </summary>
        public static string PourExecuterStellariumDirectementSurCetOrdinateurLaissezLaValeurParDefautLocalhost {
            get {
                return ResourceManager.GetString("PourExecuterStellariumDirectementSurCetOrdinateurLaissezLaValeurParDefautLocalhos" +
                        "t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour vous connecter à Cartes du Ciel sur un serveur, spécifiez ici l&apos;adresse IP du serveur..
        /// </summary>
        public static string PourVousConnecterACartesDuCielSurUnServeurSpecifiezIciLAdresseIPDuServeur {
            get {
                return ResourceManager.GetString("PourVousConnecterACartesDuCielSurUnServeurSpecifiezIciLAdresseIPDuServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RA.
        /// </summary>
        public static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RA (J2000).
        /// </summary>
        public static string RAJ2000 {
            get {
                return ResourceManager.GetString("RAJ2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rank min..
        /// </summary>
        public static string RankMin {
            get {
                return ResourceManager.GetString("RankMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scoring.
        /// </summary>
        public static string Scoring {
            get {
                return ResourceManager.GetString("Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection du Capteur.
        /// </summary>
        public static string SelectionDuCapteur {
            get {
                return ResourceManager.GetString("SelectionDuCapteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serveur.
        /// </summary>
        public static string Serveur {
            get {
                return ResourceManager.GetString("Serveur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        public static string Suivant {
            get {
                return ResourceManager.GetString("Suivant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose.
        /// </summary>
        public static string TempsDePose {
            get {
                return ResourceManager.GetString("TempsDePose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose max..
        /// </summary>
        public static string TempsDePoseMax {
            get {
                return ResourceManager.GetString("TempsDePoseMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps de pose (secondes) sans rotation de champs.
        /// </summary>
        public static string TempsDePoseSecondesSansRotationDeChamps {
            get {
                return ResourceManager.GetString("TempsDePoseSecondesSansRotationDeChamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer.
        /// </summary>
        public static string Terminer {
            get {
                return ResourceManager.GetString("Terminer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        public static string Tous {
            get {
                return ResourceManager.GetString("Tous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors du téléchargement. Fichier téléchargé non présent.
        /// </summary>
        public static string UneErreurEstSurvenueLorsDuTelechargementFichierTelechargeNonPresent {
            get {
                return ResourceManager.GetString("UneErreurEstSurvenueLorsDuTelechargementFichierTelechargeNonPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visualisation.
        /// </summary>
        public static string Visualisation {
            get {
                return ResourceManager.GetString("Visualisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous aller télécharger et mettre à jour le fichier de configuration des.
        /// </summary>
        public static string VousAllerTeléchargerEtMettreAJourLeFichierDeConfigurationDes {
            get {
                return ResourceManager.GetString("VousAllerTeléchargerEtMettreAJourLeFichierDeConfigurationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zones du ciel exclues.
        /// </summary>
        public static string ZonesDuCielExclues {
            get {
                return ResourceManager.GetString("ZonesDuCielExclues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zones exclues.
        /// </summary>
        public static string ZonesExclues {
            get {
                return ResourceManager.GetString("ZonesExclues", resourceCulture);
            }
        }
    }
}
