//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationTools.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cartes du Ciel.
        /// </summary>
        public static string CartesDuCiel {
            get {
                return ResourceManager.GetString("CartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonctionnalité non disponible pour la version 0.22.X de Stellarium.
        /// </summary>
        public static string FonctionnaliteNonDisponiblePourLaVersion022XDeStellarium {
            get {
                return ResourceManager.GetString("FonctionnaliteNonDisponiblePourLaVersion022XDeStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de créer de nouvelle carte. Nombre max. atteint ?.
        /// </summary>
        public static string ImpossibleDeCreerDeNouvelleCarteNombreMaxAtteint {
            get {
                return ResourceManager.GetString("ImpossibleDeCreerDeNouvelleCarteNombreMaxAtteint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le logiciel n&apos;a pas été trouvé..
        /// </summary>
        public static string LeLogicielNAPasEteTrouve {
            get {
                return ResourceManager.GetString("LeLogicielNAPasEteTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le logiciel n&apos;est pas installé sur ce poste..
        /// </summary>
        public static string LeLogicielNEstPasInstalleSurCePoste {
            get {
                return ResourceManager.GetString("LeLogicielNEstPasInstalleSurCePoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le serveur n&apos;est pas activé..
        /// </summary>
        public static string LeServeurNEstPasActive {
            get {
                return ResourceManager.GetString("LeServeurNEstPasActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NE.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NO.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à O.
        /// </summary>
        public static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet céleste non trouvé..
        /// </summary>
        public static string ObjetCelesteNonTrouve {
            get {
                return ResourceManager.GetString("ObjetCelesteNonTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SE.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SO.
        /// </summary>
        public static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stellarium.
        /// </summary>
        public static string Stellarium {
            get {
                return ResourceManager.GetString("Stellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une autre action est actuellement en cours..
        /// </summary>
        public static string UneAutreActionEstActuellementEnCours {
            get {
                return ResourceManager.GetString("UneAutreActionEstActuellementEnCours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue.
        /// </summary>
        public static string UneErreurEstSurvenue {
            get {
                return ResourceManager.GetString("UneErreurEstSurvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de l&apos;envoi de la commande..
        /// </summary>
        public static string UneErreurEstSurvenueLorsDeLEnvoiDeLaCommande {
            get {
                return ResourceManager.GetString("UneErreurEstSurvenueLorsDeLEnvoiDeLaCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de l&apos;ouverture du logiciel..
        /// </summary>
        public static string UneErreurEstSurvenueLorsDeLOuvertureDuLogiciel {
            get {
                return ResourceManager.GetString("UneErreurEstSurvenueLorsDeLOuvertureDuLogiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez démarrer le logiciel au moins une fois afin de terminer sa configuration..
        /// </summary>
        public static string VeuillezDemarrerLeLogicielAuMoinsUneFoisAfinDeTerminerSaConfiguration {
            get {
                return ResourceManager.GetString("VeuillezDemarrerLeLogicielAuMoinsUneFoisAfinDeTerminerSaConfiguration", resourceCulture);
            }
        }
    }
}
